#!/usr/bin/env node
/**
 * help.mjs — prints available pipeline commands with flags and examples.
 *
 * Can be run two ways:
 *   - From the RELEASE dir:  npm run help
 *   - From the PROJECT dir:  node contexts/tools/help.mjs
 */

const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const CYAN = '\x1b[36m';
const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RESET = '\x1b[0m';

const useColor = process.stdout.isTTY;
const c = (code, s) => useColor ? `${code}${s}${RESET}` : s;

console.log(`
${c(BOLD, 'Agent Pipeline v11 — available commands')}

${c(DIM, 'Dual-host: installs to Cursor (.cursor/) or Claude Code (.claude/)')}
${c(DIM, 'Projects have NO package.json / node_modules — tools run with plain `node`.')}

${c(BOLD + CYAN, 'Install (from the release dir — where you unzipped the pipeline)')}

  ${c(GREEN, 'npm run install-pipeline -- --project-root <path>')}
      Default target: Cursor. Installs to .cursor/ with .mdc rules and flat
      skills. Auto-creates <path> if its parent exists. Preserves existing
      pipeline.yaml and project-context.md.

  ${c(GREEN, 'npm run install-pipeline:cursor -- --project-root <path>')}
      Same as default, made explicit. Writes .cursor/{agents,rules,skills}/.

  ${c(GREEN, 'npm run install-pipeline:claude -- --project-root <path>')}
      Target: Claude Code. Writes .claude/{agents,rules,skills}/. Rules are
      .md (no alwaysApply), skills are <n>/SKILL.md directories.

  ${c(GREEN, 'npm run install-pipeline -- --output-dir <path> --target <host>')}
      Build into a staging directory for later manual copy. Use when target
      is on a different machine. Copy .cursor (or .claude) + contexts/ to
      the target — no other files needed.

  ${c(DIM, 'Available flags:')}
    --target <host>          cursor (default) or claude
    --project-root <path>    target project root (auto-creates if parent exists)
    --output-dir <path>      staging dir (mutually exclusive with --project-root)
    --pack <n>               which pack to install (default: your-project)
    --no-pack                kernel only, no pack
    --force-config           overwrite all pipeline split files + project-context.md from pack seed
                             (backs up first; loses analyzer-written content unless cherry-picked back)
    --merge-config           re-install pack seed but PRESERVE analyzer-owned sections (shared_paths,
                             operation_patterns, i18n, analyzer_ignore). Pack-owned sections (mcp_servers,
                             skills, builds, runtime, jira, …) take the new pack content. Use this when
                             upgrading the pack and you want new pack changes WITHOUT losing analyzer state.
                             Mutually exclusive with --force-config.
    --no-mcp                 skip mcp.sample.json generation
    --no-validate            skip post-install validation
    --dry-run                preview without changes
    --list-packs             list available packs

${c(BOLD + CYAN, 'Host layout differences')}

  ${c(DIM, 'Cursor')}     .cursor/agents/*.md    .cursor/rules/*.mdc    .cursor/skills/*.md
  ${c(DIM, 'Claude Code')}.claude/agents/*.md    .claude/rules/*.md     .claude/skills/<n>/SKILL.md
  ${c(DIM, 'MCP (Cursor)')}     ~/.cursor/mcp.json OR <repo>/.cursor/mcp.json (personal, gitignored)
  ${c(DIM, 'MCP (Claude Code)')}~/.claude.json OR <repo>/.mcp.json (team-committed, at repo root)

${c(BOLD + CYAN, 'Validate (from the project dir — where the pipeline was installed)')}

  ${c(GREEN, 'node contexts/tools/validate.mjs')}
      Run the 10 validator checks against pipeline.yaml. Discovers skills
      and agents in both .cursor/ and .claude/ automatically.

  ${c(GREEN, 'node contexts/tools/validate.mjs --quiet')}
      CI-friendly: silent on success, errors on failure.

  ${c(GREEN, 'node contexts/tools/validate.mjs --update-catalog')}
      Regenerate contexts/config/_catalog.md (human-readable layer reference).
      Run after editing skills.layer_map, aliases, subagents, or extra_triggers.

  ${c(GREEN, 'node contexts/tools/validate.mjs --emit-catalog')}
      Print the catalog to stdout without writing.

${c(BOLD + CYAN, 'MCP sample (from the project dir)')}

  ${c(GREEN, 'node contexts/tools/mcp-sample-generator.mjs --project-root .')}
      Regenerate contexts/config/mcp.sample.json + mcp.sample.README.md from
      pipeline.yaml. The sample shows developers what MCP servers to add to
      their personal Cursor/Claude Code config — the pipeline does NOT write
      to any developer's MCP config directly.

  ${c(DIM, 'mcp.sample.json is auto-generated by install-pipeline.')}
  ${c(DIM, 'Each developer copies entries from it into their own MCP config.')}

${c(BOLD + CYAN, 'Common install workflows')}

  ${c(YELLOW, '# Preview an install without touching files:')}
  ${c(GREEN, 'npm run install-pipeline -- --project-root ~/work/myproject --target claude --dry-run')}

  ${c(YELLOW, '# Re-install after pulling a new pack release (no config changes wanted):')}
  ${c(GREEN, 'npm run install-pipeline -- --project-root ~/work/myproject')}
      ${c(DIM, 'Refreshes agents/tools/skills/rules. Pipeline split files preserved.')}

  ${c(YELLOW, '# Re-install after pack seed changed AND project-analyzer ran on the dev side:')}
  ${c(GREEN, 'npm run install-pipeline -- --project-root ~/work/myproject --merge-config')}
      ${c(DIM, 'Pack-owned sections (mcp_servers, skills, builds, runtime, jira, …) take new pack content.')}
      ${c(DIM, 'Analyzer-owned sections (shared_paths, operation_patterns, i18n, analyzer_ignore) preserved.')}
      ${c(DIM, 'Old split files backed up to <file>.bak.<timestamp>.')}

  ${c(YELLOW, '# Hard reset of all configs to pack defaults (loses analyzer state):')}
  ${c(GREEN, 'npm run install-pipeline -- --project-root ~/work/myproject --force-config')}
      ${c(DIM, 'After this, re-run project-analyzer agent to rebuild shared_paths from disk.')}

${c(BOLD + CYAN, 'After editing pipeline.yaml — what to run (from the project dir)')}

  ${c(DIM, 'What you changed')}                                      ${c(DIM, 'What to run')}
  Any edit (sanity check before committing)        ${c(GREEN, 'node contexts/tools/validate.mjs')}

  skills.layer_map, aliases, extra_triggers,       ${c(GREEN, 'node contexts/tools/validate.mjs --update-catalog')}
  subagents, or orchestrator/explorer skills       ${c(DIM, '(runs checks AND regenerates _catalog.md)')}

  mcp_servers (added, removed, or changed)         ${c(GREEN, 'node contexts/tools/mcp-sample-generator.mjs --project-root .')}
                                                   ${c(DIM, '(rewrites mcp.sample.json + mcp.sample.README.md)')}

  builds, runtime, jira, meta, explorer_paths      ${c(GREEN, 'node contexts/tools/validate.mjs')}
                                                   ${c(DIM, '(no catalog/sample to regenerate — just validate)')}

  ${c(DIM, 'When in doubt, just run both:')}
  ${c(GREEN, 'node contexts/tools/validate.mjs --update-catalog')}
  ${c(GREEN, 'node contexts/tools/mcp-sample-generator.mjs --project-root .')}

  ${c(DIM, 'Then commit the edited pipeline.yaml alongside _catalog.md and mcp.sample.*')}
  ${c(DIM, 'so teammates see the updated reference material on their next pull.')}

${c(BOLD + CYAN, 'Other workflows')}

  ${c(YELLOW, '# Fresh install (Cursor, from release dir):')}
  ${c(GREEN, 'npm install && npm run install-pipeline -- --project-root ~/work/myproject')}

  ${c(YELLOW, '# Fresh install (Claude Code, from release dir):')}
  ${c(GREEN, 'npm install && npm run install-pipeline:claude -- --project-root ~/work/myproject')}

  ${c(YELLOW, '# Install BOTH hosts into the same project (they coexist):')}
  ${c(GREEN, 'npm run install-pipeline:cursor -- --project-root ~/work/myproject')}
  ${c(GREEN, 'npm run install-pipeline:claude -- --project-root ~/work/myproject')}

  ${c(YELLOW, '# In CI (from project dir — non-zero exit on any validation failure):')}
  ${c(GREEN, 'node contexts/tools/validate.mjs --quiet')}

${c(DIM, 'For flag details on any tool, run it with --help:')}
  ${c(DIM, 'node contexts/tools/install.mjs --help')}
  ${c(DIM, 'node contexts/tools/validate.mjs --help')}

${c(DIM, 'Docs: README.md · HOW-TO-USE.md · contexts/tools/README.md')}
${c(DIM, 'MCP setup: contexts/config/mcp.sample.README.md (generated after install)')}
`);
